site_name: Полезности Aurora OS
site_author: Vitaliy Zarubin
site_description: >-
  Полезности которые могут пригодиться для разработки на Aurora OS

# Repository
repo_name: 'Полезности Aurora OS'
repo_url: 'https://github.com/keygenqt/awesome-aurora'

# Navigation
nav:
  - Главная:
      - Index: index.md
      - Qt Links:
          - Qt: https://doc.qt.io/
          - Layouts: https://doc.qt.io/QT-5/qtquicklayouts-overview.html
      - Aurora Docs:
          - Иконки: https://community.omprussia.ru/documentation/software_development/reference/icons.html
          - Компоненты: https://community.omprussia.ru/documentation/software_development/reference/silica/silica-reference.html
      - Aurora Links:
          - SDK: https://www.omp.ru/sdk
          - Aurora OS: https://auroraos.ru/
          - Устройства: https://auroraos.ru/devices
          - Документация: https://auroraos.ru/documentation
  - Публикации:
      - Index: publications/index.md
      - Видео: publications/video.md
      - Cтатьи: publications/articles.md
      - Презентации: publications/presentations.md
  - Примеры:
      - Index: examples/index.md
      - ViewModel (Qt/Qml): examples/view-model.md
  - Open Source:
      - Index: open-source/index.md
      - Shop 7 in 1 : open-source/shop-7-1.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Configuration
theme:
  name: 'material'
  language: 'ru'
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono