site_name: Полезности Aurora OS
site_author: Vitaliy Zarubin
site_description: >-
  Полезности которые могут пригодиться для разработки на Aurora OS

# Repository
repo_name: 'Полезности Aurora OS'
repo_url: 'https://github.com/keygenqt/awesome-aurora'

# Navigation
nav:
  - Главная:
      - Index: index.md
      - Aврора:
        - Портал разработчиков: https://developer.auroraos.ru/
        - Aврора SDK: https://developer.auroraos.ru/doc/software_development/sdk/downloads#4-0-2-209
        - Aврора Platform SDK: https://developer.auroraos.ru/doc/software_development/psdk/downloads#4-0-2-209
        - UI Kit Aврора: https://www.figma.com/community/file/1070268277075531514/Aurora-4.0-UI-Kit
      - Community Links:
        - Telegram: https://t.me/aurora_devs
        - YouTube: https://www.youtube.com/@AuroraOS
  - Публикации:
      - Index: publications/index.md
      - Видео: publications/video.md
      - Cтатьи: publications/articles.md
      - Презентации: publications/presentations.md
  - Open Source:
      - Index: open-source/index.md
          - Completed:
            - AuroMinesweeper: open-source/AuroMinesweeper.md
            - Aurora2048: open-source/Aurora2048.md
            - AuroraKat: open-source/AuroraKat.md
            - auroraos-tower: open-source/auroraos-tower.md
            - AuroTris: open-source/AuroTris.md
            - BarWal: open-source/BarWal.md
            - Bf4fun: open-source/Bf4fun.md
            - Cargo Dock: open-source/cargodock.md
            - DjVu-Viewer: open-source/DjVu-Viewer.md
            - FastChess: open-source/FastChess.md
            - flappyAurora: open-source/flappyAurora.md
            - harbour-advanced-camera: open-source/harbour-advanced-camera.md
            - harbour-editor: open-source/harbour-editor.md
            - harbour-fernschreiber: open-source/harbour-fernschreiber.md
            - harbour-file-browser: open-source/harbour-file-browser.md
            - harbour-lines: open-source/harbour-lines.md
            - harbour-mattermost: open-source/harbour-mattermost.md
            - harbour-seaprint: open-source/harbour-seaprint.md
            - harbour-tooter: open-source/harbour-tooter.md
            - harbour-vncscreen: open-source/harbour-vncscreen.md
            - maep-qt: open-source/maep-qt.md
            - osmscout-sailfish: open-source/osmscout-sailfish.md
            - patience-deck: open-source/patience-deck.md
            - RheniumBeta: open-source/RheniumBeta.md
            - sailfish-barcode: open-source/sailfish-barcode.md
            - sailfish-quake2: open-source/sailfish-quake2.md
            - sailfish-solarsystem: open-source/sailfish-solarsystem.md
            - sailotp: open-source/sailotp.md
            - SailTuner: open-source/SailTuner.md
            - Shop 7 in 1 : open-source/shop-7-1.md
            - Stellarium-sailfishos: open-source/Stellarium-sailfishos.md
            - vs: open-source/vs.md
            - WebDRIVE2: open-source/WebDRIVE2.md
            - ytpwa: open-source/ytpwa.md
          - Developing:
            - AuroCast: open-source/AuroCast.md
            - sailfish-gpsinfo: open-source/sailfish-gpsinfo.md
            - Whoosh! In the Dungeon: open-source/Whoosh-In-the-Dungeon.md
  - Helps:
      - Helps: helps/index.md
      - Toast in Aurora OS: 'helps/_1/index.md'
  - FAQ:
      - Index: faq/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Configuration
theme:
  name: 'material'
  language: 'ru'
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono