site_name: Useful Links Aurora OS

# Repository
repo_name: 'Useful Links Aurora OS'
repo_url: 'https://github.com/keygenqt/av-useful-links'

# Navigation
nav:
  - 'Overview': index.md

# Configuration
theme:
  name: null
  custom_dir: 'cinder'