site_name: Полезности Aurora OS
site_author: Vitaliy Zarubin
site_description: >-
  Полезности которые могут пригодиться для разработки на Aurora OS

# Repository
repo_name: 'Полезности Aurora OS'
repo_url: 'https://github.com/keygenqt/awesome-aurora'

# Navigation
nav:
  - Главная:
      - Index: index.md
      - Aврора:
        - Портал разработчиков: https://developer.auroraos.ru/
        - Aврора SDK: https://developer.auroraos.ru/doc/software_development/sdk/downloads#4-0-2-209
        - Aврора Platform SDK: https://developer.auroraos.ru/doc/software_development/psdk/downloads#4-0-2-209
        - UI Kit Aврора: https://www.figma.com/community/file/1070268277075531514/Aurora-4.0-UI-Kit
      - Community Links:
          - Telegram: https://t.me/aurora_devs
          - Helps: https://keygenqt.github.io/articles/helps/
          - YouTube: https://www.youtube.com/@AuroraOS
  - Публикации:
      - Index: publications/index.md
      - Видео: publications/video.md
      - Cтатьи: publications/articles.md
      - Презентации: publications/presentations.md
  - Open Source:
      - Index: open-source/index.md
      - Shop 7 in 1 : open-source/shop-7-1.md
  - FAQ:
      - Index: faq/index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Configuration
theme:
  name: 'material'
  language: 'ru'
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono