site_name: Полезные ссылки Aurora OS
site_author: Vitaliy Zarubin
site_description: >-
  Полезные ссылки которые могут пригодиться для разработки на Aurora OS

# Repository
repo_name: 'Полезные ссылки Aurora OS'
repo_url: 'https://github.com/keygenqt/av-useful-links'

# Navigation
nav:
  - Home: index.md
  - SDK:
      - Index: sdk/index.md
      - 'Test': sdk/index.md
      - 'Test 2': sdk/index.md
  - 'Qt':
      - 'Index': qt/index.md
  - 'KMM':
      - 'Index': kmm/index.md
  - 'Other':
      - 'Index': other/index.md

# Configuration
theme:
  name: 'material'
  language: 'ru'
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono